### PR TITLE
Add NSF acknowledgments to README.md

### PR DESCRIPTION
**Pull request by jpober**
## Description

Added CSSI grant numbers from Brown and UW

## Motivation and Context

For better reporting to NSF.

## Types of changes
- [x] Documentation change (documentation changes only)

## Checklist:
- [x] I have read the [contribution guide](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/main/.github/CONTRIBUTING.md).
- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by plaplant** [comment]
@jpober @bhazelton while we're updating the README, can I change my affiliation as part of this PR? Keep forgetting to do it...

**Comment by jpober** [comment]
@plaplant, sounds good to me!

**Comment by bhazelton** [comment]
If we merge #1242 we can rebase this one to fix the coverage reporting. I need an approval on that one.

**Comment by jpober** [comment]
Ok, I'm not sure I understand Matt's comment on #1242 enough to review that one.  But if it's (in your opinion) sufficiently addressed and we're just stuck waiting for his holiday break to end, I can approve it.

**Comment by bhazelton** [comment]
yes, I changed it to do it the way he suggested.

**Review by bhazelton — APPROVED** [review]

**Pull request merged**
