### PR TITLE
Remove py2

### PR DESCRIPTION
**Pull request by steven-murray**
## Description

This attempts to remove all PY2-specific code from the repo.

## Motivation and Context

This is meant for the 2.0.0 release, and simplifies the code somewhat. Also removes py2 tests.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change (documentation changes only)
- [ ] Version change
- [ ] Build or continuous integration change

Breaking change checklist:  
- [ ] I have updated the docstrings associated with my change using the [numpy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html).
- [ ] I have updated the tutorial to reflect my changes (if appropriate).
- [ ] My change includes backwards compatibility and deprecation warnings (if possible).
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests pass in both python 2 and python 3.
- [x] I have updated the [CHANGELOG](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by mkolopanis** [comment]
We don't use appveyor, so I understand wanting to delete the yaml file. I think @bhazelton was the one interested in getting Windows tests running but `_miriad` won't compile if I remember correctly. Perhaps there is more information here?

**Comment by bhazelton** [comment]
It can go away. I do want to get it working on windows (maybe sans Miriad support) but I can always get it back. Not even sure if appveyor is the right service anymore. The file dates from the JOSS paper when the reviewer asked us to setup CI (we didn't have it before), including on appveyor but I couldn't get it working because of our reliance on aipy at the time.

**Comment by mkolopanis** [comment]
also please make sure to use the [github referencing language](https://help.github.com/en/github/writing-on-github/autolinked-references-and-urls#issues-and-pull-requests) for issue #550 in the head comment of this thread.

**Comment by mkolopanis** [comment]
I know `version.py` is about to change too, but I think we don't need this chunk of code anymore. it just is used to check for python 2 vs 3 and better to just get it out now I think.
https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/703c96f8774cd2a86d4b782cc4a69fc6940bdda4/pyuvdata/version.py#L15-L17

**Pull request merged**
