### PR TITLE
Fix handling of FHD antenna positions and Cotter telescope frame

### LINKED ISSUE #942: FHD antenna positions are not handled correctly
FHD antenna positions come directly from uvfits, so they are relative rotated ECEF frame just like uvfits antenna positions. Currently they are being treated as if they are in relative ECEF coordinates, which yields incorrect results.

### PR DESCRIPTION
**Pull request by bhazelton**
## Description

Properly treat FHD antenna positions as being in the relative rotated ECEF frame, just like uvfits antenna positions. Add a test against raw MWA correlator files and a Cotter derived file to verify the conversion, which fails on `main`.

Also fix the handling of the telescope frame for Cotter. Cotter leaves out this information, which led to using the known telescope location. But that meant that the reference position for the antenna positions changed without the antenna positions being properly updated. Now we detect that it is a Cotter file and set the telescope frame to 'ITRF' as it should be.

## Motivation and Context

Fixes #942 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change (documentation changes only)
- [ ] Version change
- [ ] Build or continuous integration change

## Checklist:

- [x] I have read the [contribution guide](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/main/.github/CONTRIBUTING.md).
- [x] My code follows the code style of this project.

Bug fix checklist:
- [x] My fix includes a new test that breaks as a result of the bug (if possible).
- [x] All new and existing tests pass.
- [x] I have updated the [CHANGELOG](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/main/CHANGELOG.md).

### CODE REVIEW

**Review by plaplant — DISMISSED** [review]
Looks good, thanks @bhazelton!

**Comment by bhazelton** [comment]
Still needs a changelog

**Comment by nicholebarry** [comment]
This fix outputs the correct, expected tile positions from FHD sav files that have gone through Cotter.

**Comment by bhazelton** [comment]
@plaplant I think this is ready for a re-review when you have time. It had to be rebased after the UVCal metadata changes.

**Review by plaplant — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
