### PR TITLE
Fix a bug in fhd_cal

### LINKED ISSUE #490: UVCal.read_fhd_cal returns gains ~2
The UVCal.read_fhd_cal function returns gains that are exactly twice those used internally in FHD. Is there a reason for this? If not we should correct it.

### PR DESCRIPTION
**Pull request by bhazelton**
## Description

Fix a copy/paste bug in fhd_cal that may explain an open bug report.

## Motivation and Context

I was doing some code cleanup with flake8, which pointed out that there was an unused variable. Examining the code, I think it was the result of a copy/paste error and I think it may fix issue #490 where FHD calibration solutions were getting doubled.

I need some testing to verify it fixes that bug.
edit: Ruby confirmed it fixed the bug.
fixes #490

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change (documentation changes only)
- [ ] Version change
- [ ] Build or continuous integration change

## Checklist:

- [x] I have read the [contribution guide](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/master/.github/CONTRIBUTING.md).
- [x] My code follows the code style of this project.

Bug fix checklist:
- [x] My fix includes a new test that breaks as a result of the bug (if possible).
- [x] All new and existing tests pass in both python 2 and python 3.
- [x] I have updated the [CHANGELOG](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by bhazelton** [comment]
@rlbyrne could you test this branch to see if it fixes the issue? If it does, we need to add a unit test that fails on master as a result of this bug and passes on this branch.

**Comment by bhazelton** [comment]
And this is erroring because of a problem with the test file that was exposed by this fix. In the test file we have a different number of antennas and frequencies in the fit gain array than in the residual gain array.

**Comment by rlbyrne** [comment]
I've tested this PR and confirmed that it resolves issue #490. Thank you!

**Comment by adampbeardsley** [comment]
Just FYI - it looks like when you wrote "may fix #490", github would have closed the issue when we merge this. It's fine since Ruby confirmed, but may want to be careful in the future.

**Comment by bhazelton** [comment]
Oops! I'll be more careful next time. And I'll also update the top message to say it does since Ruby confirmed.

**Comment by bhazelton** [comment]
@adampbeardsley I had to rebase because of another PR merge, can you re-approve?

**Pull request merged**
