### PR TITLE
Remove polarization warning on multi-pol read

### LINKED ISSUE #888: polarization concatenation order and possible errors in writing output files
When concatenating files with different polarizations, the order in which they are read in (using the `read` method), or possibly added, can generate the error 

`Combined polarizations are not evenly spaced. This will make it impossible to write this data out to some file types.`

If the read order is `['xx','yy','xy','yx']` (AIPS ordering), this error is not generated.  The underlying problem is apparently that uvfits requires a specific order if all 4 are present.

Suggest allowing a read in any order (since pyuvdata doesn't appear to fundamentally care), but enforcing AIPS ordering on writing uvfits files (or other formats which require a particular order).

### PR DESCRIPTION
**Pull request by plaplant**
## Description

There is an issue where in the middle of reading files and combining along polarization, a spurious warning could be issued if the files were not read in using AIPS order. This is somewhat unfriendly to the user, and so we have removed this warning. We have also made it so files where the polarization order matters (currently just UVFITS) will reorder the polarization array on-the-fly, so that the user does not need to worry about polarizations being potentially out of order.

## Motivation and Context

This warning was originally issued in the case that the user wanted to write out to UVFITS, as it is the only file format we write that is particular about polarization order and spacing. However, this warning was overzealous, and would print out mid-read without checking the final object. We have made it so there is no warning, and instead an error is raised if the polarization axis is incompatible with writing a UVFITS file.

Closes #888.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change (documentation changes only)
- [ ] Version change
- [ ] Build or continuous integration change

## Checklist:

- [x] I have read the [contribution guide](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/main/.github/CONTRIBUTING.md).
- [x] My code follows the code style of this project.

Bug fix checklist:
- [ ] My fix includes a new test that breaks as a result of the bug (if possible).
- [x] All new and existing tests pass.
- [ ] I have updated the [CHANGELOG](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/main/CHANGELOG.md).

### CODE REVIEW

**Review by bhazelton — COMMENTED** [review]
This looks great! It looks like we don't sort the pols in the add method like we do the frequencies. Should we maybe add that?

**Comment by plaplant** [comment]
@bhazelton I think we do sort it maybe? It looks like the relevant part of `__add__` is here:

https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/1ba3ccd13be24fcadc1e1dc470e7d5fcef14d3c4/pyuvdata/uvdata/uvdata.py#L3939-L3942

I think the `np.argsort` will reorder the polarizations by their absolute value, because we then index into the polarization axis of the combined arrays using `p_order`. We also have part of a test that explicitly adds the polarizations in the wrong order, and checks that they match the ordered original:

https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/1ba3ccd13be24fcadc1e1dc470e7d5fcef14d3c4/pyuvdata/uvdata/tests/test_uvdata.py#L3179-L3186

**Comment by bhazelton** [comment]
oops, I guess I missed the pol reordering, glad it's there.

**Review by bhazelton — APPROVED** [review]
Looks good, thanks! I note that I don't think this needs a changelog entry because it is only removing a warning that is often spurious, it isn't changing functionality.

**Pull request merged**
