### PR TITLE
Remove Deprecate code marked for version > 1.5

### PR DESCRIPTION
**Pull request by mkolopanis**
Removes all code which deprecation versions > 1.5

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change (documentation changes only)
- [ ] Version change
- [ ] Build or continuous integration change

## Checklist:

- [x] I have read the [contribution guide](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/master/.github/CONTRIBUTING.md).
- [x] My code follows the code style of this project.

Breaking change checklist:  
- [x] I have updated the docstrings associated with my change using the [numpy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html).
- [ ] I have updated the tutorial to reflect my changes (if appropriate).
- [ ] My change includes backwards compatibility and deprecation warnings (if possible).
- [x] I have added tests to cover my changes.
- [x] All new and existing tests pass.
- [x] I have updated the [CHANGELOG](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by mkolopanis** [comment]
Hmm it says there are 2 new line misses but I am having trouble identifying them

**Comment by bhazelton** [comment]
@mkolopanis would `conftestpy` be used in it's old location if we ran a command from the top-level directory but specified the `pyuvdata/uvdata/tests` directory?

**Comment by mkolopanis** [comment]
I _feel_ like I tried this and it didn't work, only just running `pytest` would make it work. I'll take another look though and try.

**Comment by mkolopanis** [comment]
Looks like the answer is no. It does not make the appropriate test files. We could add conftests to each of the test subdirectories.

**Comment by bhazelton** [comment]
I'm ok with it being where it is now, just trying to understand the issues.

**Pull request merged**
