### PR TITLE
Add method to reorder data along the blt axis

### LINKED ISSUE #427: make methods to re-order data along blt axis
1) method to pick which axis (baseline or time) changes fastest
2) method optimized for baseline dependent averaging (sensible striding)

### LINKED ISSUE #502: consolidate conjugation operations on UVData object, make option to convert to j>i
helpful for pyuvsim & others

### PR DESCRIPTION
**Pull request by bhazelton**
## Description

Add two new methods:
- `UVData.conjugate_bls` to conjugate baselines to get the desired baseline directions
- `UVData.reorder_blts` to reorder the data along the blt axis (and optionally also conjugate baselines), which is needed for several different use cases.
- Also added support in read/write for a new `blt_order` optional parameter that can keep track of how the blt axis is ordered.

## Motivation and Context

closes #427 
closes #502

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change (documentation changes only)
- [ ] Version change
- [ ] Build or continuous integration change

## Checklist:

- [x] I have read the [contribution guide](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/master/.github/CONTRIBUTING.md).
- [x] My code follows the code style of this project.

New feature checklist:
- [x] I have added or updated the docstrings associated with my feature using the [numpy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html).
- [x] I have updated the tutorial to highlight my new feature (if appropriate).
- [x] I have added tests to cover my new feature.
- [x] All new and existing tests pass in both python 2 and python 3.
- [x] I have updated the [CHANGELOG](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by bhazelton** [comment]
Maybe add an optional parameter to UVData to keep track of sort order.

**Comment by bhazelton** [comment]
@jpober are you still up for reviewing this PR?

**Comment by jpober** [comment]
Yes, I got my grading done yesterday.  Probably another couple of days before I make it that far down on my to do list...

**Comment by bhazelton** [comment]
thanks!

**Comment by bhazelton** [comment]
@jpober It's a UVParameter attribute on UVData, so it's included in the list of UVData parameters. You can see it on read the docs here: https://pyuvdata.readthedocs.io/en/reorder_blt/uvdata_parameters.html

**Pull request merged**
