### PR TITLE
Fix Mac and python 3.8 tests

### PR DESCRIPTION
**Pull request by bhazelton**
## Description

Commented out the conda update step. This seems to fix the issues we've been having lately with conda on Mac and with python 3.8 on Linux.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change (documentation changes only)
- [ ] Version change
- [x] Build or continuous integration change

## Checklist:

- [x] I have read the [contribution guide](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/master/.github/CONTRIBUTING.md).
- [x] My code follows the code style of this project.

Build or continuous integration change checklist:
- [ ] If required or optional dependencies have changed (including version numbers), I have updated the readme to reflect this.
- [ ] If this is a new CI setup, I have added the associated badge to the readme and to references/make_index.py (if appropriate).

### CODE REVIEW

**Comment by bhazelton** [comment]
@mkolopanis We use the miniconda latest package, is that enough to ensure that we're on a relatively recent version but maybe not the bleeding edge?

**Comment by mkolopanis** [comment]
Yeah I'm not totally sure :thinking: We can just keep monitoring though I suppose? I would hope the miniconda/latest we use on circleci would be good though yeah.

**Comment by bhazelton** [comment]
We use miniconda latest on github actions too!

**Comment by mkolopanis** [comment]
oh yeah good point.

**Pull request merged**
