### PR TITLE
Warning cleanup

### PR DESCRIPTION
**Pull request by bhazelton**
## Description
Catch warnings in tests that weren't being caught. Move towards better warning & error handling in some tests:
- Use pytest's warning filtering mechanism for warnings unrelated to tests  (as opposed to checkWarning that really should be used for warnings that are related to the tests).
- Check that error messages are as expected (not just that errors are raised).

## Motivation and Context
Several uncaught warnings had crept into the tests. The logs shown on CircleCI were cut off before the warning section, so it was hard to tell from them that warnings weren't being caught. I removed the `-v` argument to pytest on CircleCI to shorten the logs.

While tackling the uncaught warnings, I went ahead and improved the warning and error handling in `test_miriad`, `test_uvfits` and some of the tests in `test_uvdata`. And I fixed one small bug that was exposed in this process (a warning was raised inappropriately). I don't really thing it merits a line in the changelog.

I also streamlined the circleci config to make sure there weren't differences in how the minimum dependencies tests were run because we were having weird errors with them.

## Types of changes
None of these types really apply. I guess bug fix is closest.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change (documentation changes only)
- [ ] Version change
- [x] Build or continuous integration change

## Checklist:
- [x] I have read the [contribution guide](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/master/.github/CONTRIBUTING.md).
- [x] My code follows the code style of this project.

Bug fix checklist:
- [x] My fix includes a new test that breaks as a result of the bug (if possible).
- [x] All new and existing tests pass in both python 2 and python 3.
- [ ] I have updated the [CHANGELOG](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by bhazelton** [comment]
There seems to be a new miriad runtime error popping up sometimes on this branch. It's intermittent and usually goes away if the tests are re-run. I don't know how any of the changes I made could be causing this. But I'm worried about bringing this problem into the master branch.

**Comment by steven-murray** [comment]
I'll try have a look at this tomorrow, if no-one else solves it before then.

**Comment by mkolopanis** [comment]
I've been trying to re-create this on fresh docker images to no success :frowning_face:

**Comment by bhazelton** [comment]
hmm. I'm going to rebase because recent PR merges requires that. We'll see if the errors re-appear.

**Comment by bhazelton** [comment]
Oh man. We have the problem we were seeing before on the CircleCI 3.7 build, but we also have a whole new set of errors I've never seen before on the Azure builds. I really thought this was a very straightforward PR.

**Comment by mkolopanis** [comment]
oh I misspoke earlier I _can_ reproduce this, even without a fresh image with python 3.7

**Comment by bhazelton** [comment]
oh, I hadn't thought about it being python 3.7 specific. That's a good clue. I'm not sure how to pursue it though...

**Comment by mkolopanis** [comment]
It really doesn't make much sense to me but here's some behavior I have noticed. If I rebuild the miriad extension I will get there error, even running the tests a few times in a row. If I change the test_miriad file ( by deleting then re initializing uv_in, or re-writing write_file) the error goes away, but if I the remove the edit the error stays away and won't come back until I re-build the extension.

Not sure how much of that is useful clues or red herrings. Just my observations.

**Comment by mkolopanis** [comment]
I've seen those iers issues on a local fresh build, usually fixed by restarting. not sure why hera_cal suddenly doesn't like us though.

**Comment by bhazelton** [comment]
Ok, this seems to be fixed. Can I get someone to review it?

**Pull request merged**
