### PR TITLE
add metadata_only property, allow metadata only reads of multiple files

### LINKED ISSUE #621: Add uv objects which are metadata only
Should enable setting read_data=False when reading _list of files_.  This solution will be similar to what was worked out for select() which has a metadata_only option.

This is critically needed to load large datasets.

### LINKED ISSUE #636: Have select on partial objects use ignore_requirements
Currently we turn off checks for selecting on partial uvdata objects.  We can now use the ignore_requirements option in check to check those that are defined.

### PR DESCRIPTION
**Pull request by bhazelton**
## Description

Add a metadata_only property to UVData objects that adjusts whether the data_array, flag_array and nsample_array are required. This allows for checking metadata only objects and makes other metadata only operations easier.

Add support for reading in multiple files with metadata only (setting read_data = False).

## Motivation and Context

closes #621 
closes #636 

partially addresses #637, but we could still add an iterator over the "data_like" elements.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change (documentation changes only)
- [ ] Version change
- [ ] Build or continuous integration change

## Checklist:

- [x] I have read the [contribution guide](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/master/.github/CONTRIBUTING.md).
- [x] My code follows the code style of this project.

New feature checklist:
- [x] I have added or updated the docstrings associated with my feature using the [numpy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html).
- [ ] I have updated the tutorial to highlight my new feature (if appropriate).
- [x] I have added tests to cover my new feature.
- [x] All new and existing tests pass in both python 2 and python 3.
- [x] I have updated the [CHANGELOG](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by bhazelton** [comment]
I took out the `metadata_only` keyword out of a couple of methods, maybe we should add them back for backwards compatibility (maybe with a deprecation period?)

**Comment by steven-murray** [comment]
@bhazelton doesn't having the keywords potentially break consistency? As in, if the object has no data, and the user specifies `metadata_only=False`, that's broken, right? 

I guess you could just add a deprecation warning if it's set by the user at all, otherwise it just gets set to the class-level attribute. If the user sets it in an inconsistent way, raise an error.

**Comment by plaplant** [comment]
@bhazelton I think we should keep the `metadata_only` in, and add a deprecation warning if there's a desire to remove them in a future version. I believe the hera_cal tests are failing right now for a genuine reason (i.e., this changeset breaks the repo's tests), not the IERS issues we've been seeing. I'm a little out of the loop as far as the issues that this PR is addressing so I need to catch up, but I'd like to at least mention that I think we should keep that keyword in for now.

**Comment by bhazelton** [comment]
Ok, I'll add the keywords back with suitable deprecation warnings and errors if they're in conflict with the property.

**Comment by bhazelton** [comment]
@dannyjacobs can you look at this PR? It's to address your issue about reading in multiple files with metadata only. We rethought how metadata only objects were handled throughout the code, cleaning it up and making more development along those lines easier.

**Pull request closed without merging**
