### PR TITLE
Add comments and code updates to clarify that the real part of the xy autos is corrected

### PR DESCRIPTION
**Pull request by bhazelton**
## Description

Fix a bug @d3v-null noticed in the MWA correlator FITS file reader.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change (documentation changes only)
- [ ] Version change
- [ ] Build or continuous integration change

## Checklist:

- [x] I have read the [contribution guide](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/main/.github/CONTRIBUTING.md).
- [x] My code follows the code style of this project.

Bug fix checklist:
- [ ] My fix includes a new test that breaks as a result of the bug (if possible).
- [x] All new and existing tests pass.
- [ ] I have updated the [CHANGELOG](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/main/CHANGELOG.md).

### CODE REVIEW

**Comment by bhazelton** [comment]
@PyxieLouStar can you look at this and make sure it's right?

**Comment by d3v-null** [comment]
I think we determined that it looks like xy aren't being corrected when you read the code, but in fact they are. It's more of a code clarity issue

**Comment by bhazelton** [comment]
ok. I think we should either do this fix or add a comment so that a future reader isn't confused. What would you prefer?

**Comment by PyxieLouStar** [comment]
I think my preference would be to add the fix and also add a comment noting something like: these autos are corrected in-place and the data_array assignment is there in case the in-place correction changes/stops working.

**Comment by bhazelton** [comment]
@PyxieLouStar I added the comments, can you take a look when you have a chance?

**Comment by PyxieLouStar** [comment]
Looks great!

**Pull request merged**
