### PR TITLE
Add an option to use the HERA gridding algorithm to find redundancies

### PR DESCRIPTION
**Pull request by bhazelton**
## Description

This adds a new option for redundancy finding to use the HERA gridding algorithm rather than the existing clustering algorithm. This has some advantages, it's faster and will not throw errors, but it might not handle non-redundant arrays well and the tolerance needs to be well specified to be less than half the minimal antenna spacing.

I also fixed what I am pretty convinced is a bug for data sets that are not rectangular in the basline-times where baselines could be compared at different times. I now use the antenna positions to get ENU baseline vectors if the object is not rectangular in baseline-times. This bug surfaced when I was testing the new HERA algorithm.

~Questions for this PR:
We could decide to just replace the existing algorithm with the HERA algorithm rather than making it an option. Or we could default it to the HERA algorithm. I'm open to any of these options. I haven't yet updated the changelog because I wasn't sure which direction we wanted to go.~
We decided to make the new method the default but with a warning message that the default had changed.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change (documentation changes only)
- [ ] Version change
- [ ] Build or continuous integration change

## Checklist:

- [x] I have read the [contribution guide](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/main/.github/CONTRIBUTING.md).
- [x] My code follows the code style of this project.

Bug fix checklist:
- [x] My fix includes a new test that breaks as a result of the bug (if possible).
- [x] All new and existing tests pass.
- [x] I have updated the [CHANGELOG](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/main/CHANGELOG.md).

New feature checklist:
- [x] I have added or updated the docstrings associated with my feature using the [numpy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html).
- [ ] I have updated the tutorial to highlight my new feature (if appropriate).
- [x] I have added tests to cover my new feature.
- [x] All new and existing tests pass.
- [x] I have updated the [CHANGELOG](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/main/CHANGELOG.md).

### CODE REVIEW

**Comment by bhazelton** [comment]
I think it probably won't error on core antennas, but it could inappropriately group them in with the hex tiles. The tolerance parameter will be key to that, I haven't messed with this much for non-redundant arrays.

**Comment by baron-de-montblanc** [comment]
> @baron-de-montblanc can you take a look at this code and see if it works any better (or worse) on MWA Phase 2? It may simplify redundancy finding (i.e. no need to throw out the core antennas first).

Yes, this works well for my Phase 2 data. I set tol=3 (the minimum antenna spacing in the file was 8m) and it didn't throw any errors. In total it got rid of about 1/3 of the baselines. Interestingly enough, after the initial compression, I ran it a few more times, gradually increasing the tolerance. I increased until tol=1000 and no additional baselines were thrown out (and no errors thrown either).

**Comment by bhazelton** [comment]
> Yes, this works well for my Phase 2 data. I set tol=3 (the minimum antenna spacing in the file was 8m) and it didn't throw any errors. In total it got rid of about 1/3 of the baselines. Interestingly enough, after the initial compression, I ran it a few more times, gradually increasing the tolerance. I increased until tol=1000 and no additional baselines were thrown out (and no errors thrown either).

great! Thanks for the report.

**Comment by bhazelton** [comment]
@jpober I think the biggest question I have is should we just replace the old clustering method with this HERA-based gridding method or should we keep them both around? And if the latter, what should the default method be. I'm sort of leaning towards just replacing it but I haven't thought about this super deeply.

**Comment by jpober** [comment]
I don't have a strong opinion.  I'm slightly reluctant to remove functionality until we have dug a little deeper and confirmed the results are (dare I say) redundant.  That said, the redundancy finder was already a little confusing since we had calculations using uvws and antenna positions as separate options.  Adding a third sounds like too much.  So I'm ok with just replacing it, but maybe add a warning that there's been an update and that it's not guaranteed to reproduce older results?

**Comment by bhazelton** [comment]
On the telecon we decided to make the new method be the default but with a warning that the default has changed.

**Comment by bhazelton** [comment]
@jpober I made the change we discussed in the telecon yesterday -- I defaulted it to use the HERA algorithm but with a warning.

**Review by jpober — COMMENTED** [review]
I'm all for giving credit to the HERA team, but do we want the warnings to refer to this as the "HERA gridding based algorithm"?  I feel like for the average user this might sound like it's the algorithm for use with the HERA array, not a general algorithm from the HERA team.  Maybe we could say "Defaulting to True to use the new gridding based algorithm (developed by the HERA team) rather than the older clustering based algorithm" or something?

**Comment by bhazelton** [comment]
> I'm all for giving credit to the HERA team, but do we want the warnings to refer to this as the "HERA gridding based algorithm"? I feel like for the average user this might sound like it's the algorithm for use with the HERA array, not a general algorithm from the HERA team. Maybe we could say "Defaulting to True to use the new gridding based algorithm (developed by the HERA team) rather than the older clustering based algorithm" or something?

Yep, sounds good. I'll make that change.

**Review by jpober — APPROVED** [review]
Looks good.  Can you confirm that the error in the build against HERA Cal is expected?  If so, I'll go ahead and merge.

**Pull request merged**
