### PR TITLE
Fixed bug when beam doesn't wrap in phi

### LINKED ISSUE #941: UnboundLocalError when converting a uvbeam object to healpix with nside other than default
```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-7-2d0eee290741> in <module>
----> 1 uvb.to_healpix(nside=128)

~/src/anaconda/envs/HERA/lib/python3.7/site-packages/pyuvdata/uvbeam/uvbeam.py in to_healpix(self, nside, run_check, check_extra, run_check_acceptability, inplace)
   1993             run_check=run_check,
   1994             check_extra=check_extra,
-> 1995             run_check_acceptability=run_check_acceptability,
   1996         )
   1997 

~/src/anaconda/envs/HERA/lib/python3.7/site-packages/pyuvdata/uvbeam/uvbeam.py in interp(self, az_array, za_array, az_za_grid, healpix_nside, healpix_inds, freq_array, freq_interp_tol, polarizations, return_bandpass, reuse_spline, spline_opts, new_object, run_check, check_extra, run_check_acceptability)
   1804             freq_interp_kind=kind_use,
   1805             polarizations=polarizations,
-> 1806             **extra_keyword_dict,
   1807         )
   1808 

~/src/anaconda/envs/HERA/lib/python3.7/site-packages/pyuvdata/uvbeam/uvbeam.py in _interp_az_za_rect_spline(self, az_array, za_array, freq_array, freq_interp_kind, freq_interp_tol, polarizations, reuse_spline, spline_opts)
   1420 
   1421                         if do_interp:
-> 1422                             if np.iscomplexobj(data_use):
   1423                                 # interpolate real and imaginary parts separately
   1424                                 real_lut = interpolate.RectBivariateSpline(

UnboundLocalError: local variable 'data_use' referenced before assignment
```

### PR DESCRIPTION
**Pull request by bhazelton**
## Description

Fixed a bug that occurred when the beam didn't wrap around in phi. Also streamlined some of the beam interpolation testing code using pytest's `parametrize`.

## Motivation and Context

Fixes #941 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change (documentation changes only)
- [ ] Version change
- [ ] Build or continuous integration change

## Checklist:

- [x] I have read the [contribution guide](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/main/.github/CONTRIBUTING.md).
- [x] My code follows the code style of this project.

Bug fix checklist:
- [x] My fix includes a new test that breaks as a result of the bug (if possible).
- [x] All new and existing tests pass.
- [x] I have updated the [CHANGELOG](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/main/CHANGELOG.md).

### CODE REVIEW

**Comment by bhazelton** [comment]
@kbharatgehlot can you confirm that this PR fixes the bug you reported in #941?

**Comment by bhazelton** [comment]
@kbharatgehlot can you confirm that this PR fixes the bug you reported in #941?

**Comment by kbharatgehlot** [comment]
Yes, the PR fixed the bug.

**Review by mkolopanis — APPROVED** [review]
Looks simple and clean. Funny how an `else` can just slip by some times.

The testing updates here look good. I would be remiss If I did not mention that we probably should test explicitly against the errors being raised, especially since some of those tests were touched by this PR. That said, I am willing to punt that for another time.

**Comment by bhazelton** [comment]
Thanks for the prod @mkolopanis, I went ahead and fixed all the error checking in `test_uvbeam` to actually check the error messages (and found a few mistakes along the way that I also fixed).

**Review by plaplant — APPROVED** [review]
Thanks @bhazelton! The fix for beam wrapping looks great.

Looking at the UVBeam tests that were changed, I was wondering if it is worth the trouble to make them more modular. There seem to be some large tests that check a few different things, and it might be more efficient/instructive to break them out to separate tests. I'm also very happy to merge this as is, it was just a thought I had. I'll leave it up to you.

**Comment by bhazelton** [comment]
@plaplant probably some modularity would help, the problem is that the beam tests are still some of the slowest tests on the repo and breaking up tests can make them run slower because sometimes you have to redo work to get to the same point. I did some of that back when I made it faster using more intelligent fixtures, but there probably should be another hard look at it. If breaking things up doesn't work we could at least have comments explaining that in the longer tests.

**Comment by plaplant** [comment]
Okay that's fair enough. Let's leave this as is and I'll make an issue.

**Pull request merged**
