### PR TITLE
Add  a CI to check for warnings, fix some tests

### LINKED ISSUE #1040: Add a CI check for warnings in tests
Add a check that runs pytest with `-W error` to turn warnings into errors. Make this a non-blocking CI check so we get notified if there are warnings but it doesn't block merging PRs.

### PR DESCRIPTION
**Pull request by bhazelton**
## Description

- Add a CI run to check for warnings in tests (using `pytest -W error`). I'm not sure this should be required to pass to merge the PR, but I think we want more visibility into warnings.
- Fixed some tests that broke with this setup. They raised very cryptic `pytest.PytestUnraisableExceptionWarning` warnings that were somehow ignored under normal pytest runs so didn't show up until I tried running with the `-W error` flag. After some digging I found that it was caused by not properly closing files. I fixed those tests to use context managers.

## Motivation and Context

closes #1040 

## Types of changes

- [x] Build or continuous integration change

## Checklist:

- [x] I have read the [contribution guide](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/main/.github/CONTRIBUTING.md).
- [x] My code follows the code style of this project.

Build or continuous integration change checklist:
- [ ] If required or optional dependencies have changed (including version numbers), I have updated the readme to reflect this.
- [ ] If this is a new CI setup, I have added the associated badge to the readme and to references/make_index.py (if appropriate).

### CODE REVIEW

**Comment by kartographer** [comment]
@bhazelton -- I think this looks excellent, although just out of curiosity, have we done any sort of smoke test to make sure that a warning actually causes the new check to fail?

**Comment by bhazelton** [comment]
I have tested that the `-W error` on my local machine does what we want, I haven't smoke tested it all the way through the CI. I can make another temporary branch off this one to test that.

**Comment by bhazelton** [comment]
I tested it on a temporary branch based off this one and it appears to work as expected: https://app.circleci.com/pipelines/github/RadioAstronomySoftwareGroup/pyuvdata/2672/workflows/10d86869-fb92-4cac-aadf-bcf9ea1dbfdf/jobs/16626

**Comment by kartographer** [comment]
First time i think I've ever been excited to see a failing check 😉

**Review by kartographer — APPROVED** [review]
Looks excellent, thanks for putting this together @bhazelton!

**Pull request merged**
