### PR TITLE
Update ci ymls

### PR DESCRIPTION
**Pull request by mkolopanis**
cleaning up yam files used for external tests in ci build. 
## Description

removed verbose test output for hera_cal/hera_qm
removed `nose` install, added `pytest` to hera_cal/hera_qm yml

## Motivation and Context

No need to install unnecessary packages in test environments. 
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change (documentation changes only)
- [ ] Version change
- [x] Build or continuous integration change

## Checklist:

- [x] I have read the [contribution guide](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/master/.github/CONTRIBUTING.md).
- [x] My code follows the code style of this project.

Build or continuous integration change checklist:
- [ ] If required or optional dependencies have changed (including version numbers), I have updated the readme to reflect this.
- [ ] If this is a new CI setup, I have added the associated badge to the readme and to references/make_index.py (if appropriate).

### CODE REVIEW

**Comment by mkolopanis** [comment]
I'm holding out for PRs on pyuvsim and hera_sim to see if we can remove mpi4py from hera_cal as well.

**Comment by mkolopanis** [comment]
This is a lot of just under the hood stuff, but if there is a desire I can update the changelog

**Comment by bhazelton** [comment]
No need to add to the changelog for CI stuff that doesn't change the code.

**Comment by mkolopanis** [comment]
that failure, looks like buried iers issues?

**Comment by bhazelton** [comment]
yes, it does, but I don't understand quite what is going on.

**Comment by bhazelton** [comment]
I'm just going to rerun the job, it's not a fix but I don't quite see how to fix it at the moment.

**Pull request merged**
