### PR TITLE
Updates to Miriad file writer for compatibility with Miriad imaging tasks

### PR DESCRIPTION
**Pull request by telegraphic**
Fixes the output type for `inttim` to match that expected by Miriad, and adds some keywords needed for basic imaging with miriad.

## Description

This PR adds five keywords that required by miriad for imaging, with default values:  `jyperk`, `restfreq`, `vsource`, `veldop`, and `systemp`.

It also changes the data type for the `inttime` variable from double (float64) to 'real' (float32), as defined in miriad source code (see the [vartable.txt](https://github.com/pkgw/carma-miriad/blob/CVSHEAD/cat/vartable.txt)). This change fixes a runtime error that causes the miriad `invert` task to fail.

## Motivation and Context

Miriad expects `inttime` to be a 'real' (float32), however pyuvdata currently writes a float64 value. If `inttime` is not stored as a real, the miriad task `invert` will fail:

```
### Fatal Error: Variable inttime has the wrong data type, in UVREAD
```

This issue was encountered when attempting to image SKA-low data https://github.com/ska-sci-ops/aavs_uv/issues/36, and closes the issue.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change (documentation changes only)
- [ ] Version change
- [ ] Build or continuous integration change

## Checklist:
- [x] I have read the [contribution guide](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/main/.github/CONTRIBUTING.md).
- [x] My code follows the code style of this project.

Bug fix checklist:
- [ ] My fix includes a new test that breaks as a result of the bug (if possible).
- [x] All new and existing tests pass.
- [x] I have updated the [CHANGELOG](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/main/CHANGELOG.md).

Version change checklist:
- [x] I have updated the [CHANGELOG](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/main/CHANGELOG.md) to put all the unreleased changes under the new version (leaving the unreleased section empty).
- [X]  (N/A): I have noted any dependency changes since the last version and will update the conda package build accordingly.

### CODE REVIEW

**Comment by telegraphic** [comment]
PS: This is my first commit -- let me take the opportunity to say a huge thanks for all y'all work on this :pray:. We have been using it to write out files for the SKA-low AAVS3 station in various formats (miriad, uvfits and MS) for science verification.

**Review by bhazelton — APPROVED** [review]
Thanks for finding and fixing this! We don't have a large Miriad user base, appreciate the help.

**Comment by telegraphic** [comment]
Thanks @bhazelton, I'll have a look over the next week or so.

**Comment by telegraphic** [comment]
@bhazelton - I had some time today and added `jyperk` to the variable list, added the warning checks, and linted the code (farewell, aligned dictionary values!)

**Comment by bhazelton** [comment]
Thanks @telegraphic, sorry about the linting challenges. Most pyuvdata developers use pre-commit to take care of these linting issues for us, there are directions in the developer install section of the readme.

It looks like the tests are still failing, if you want you can run them locally by just calling `pytest` in the top-level pyuvdata folder. I'm also happy to help if you want me to.

Sorry, these details are a bit finicky. I promise they get easier!

**Comment by telegraphic** [comment]
Hi @bhazelton, I may need some hand-holding here... I think the remaining failing tests are from `test_mwa_corr_fits.py` and unrelated to my changes?

**Comment by bhazelton** [comment]
> Hi @bhazelton, I may need some hand-holding here... I think the remaining failing tests are from `test_mwa_corr_fits.py` and unrelated to my changes?

Yep, this is caused by the release of a new version of scipy and new deprecation warnings. @kartographer fixed it on main, so if you rebase your branch on our main I think they'll go away.

**Comment by bhazelton** [comment]
@telegraphic This is very close. It looks like there's small linting error and there's some warning filtering that needs to be added to some tests. An example of the kind of filtering I'm talking about is here: https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/4293cca045e091c4159cdedda8beeeee2e2d936d/pyuvdata/uvdata/tests/test_miriad.py#L1522

looks like maybe you need to add something like
`@pytest.mark.filterwarnings("ignore:writing default values for restfreq, vsource, veldop, jyperk, and systemp")`
to that test (so on line 1523) and a couple other tests.

You can test that you've fixed this by either checking that you get no warnings when you run pytest or by running `pytest -W error` to turn warnings into errors (which is what we do in the warnings test CI run). I'd suggest doing this with python < 3.12 because there are a few warnings in python 3.12 that we are waiting on 3rd party fixes on, so we're ignoring them for now.

As before, I am happy to help make these changes if you want.

**Comment by telegraphic** [comment]
> As before, I am happy to help make these changes if you want.

@bhazelton if you wouldn't mind, yes please! I'll try and do a cleaner PR next time...

**Comment by bhazelton** [comment]
@telegraphic Sorry this is finicky it takes everyone awhile to figure it all out. Your PR is great and we want it in and I'm happy to help sort out this minor stuff. Since this is from your repo's main branch, I'm going to make a PR on your repo to fix it there. When that PR is merged it should propagate to this PR (a bit circular, but I think this is the right approach).

**Comment by telegraphic** [comment]
Oop, I renamed the branch and broke it :/. I renamed the branch to `2024.01-dcp-uvfits-miriad`.

**Comment by bhazelton** [comment]
You should be able to just open a new PR from that branch, but I'd suggest merging my PR on your repo first to fix the test errors. If it'd help, I'd be happy to jump on zoom with you for a little bit to hash out the last couple issues so we can get both your PRs merged.

**Pull request closed without merging**
