### PR TITLE
Add option to return a new beam option from `interp`

### LINKED ISSUE #622: uv beam frequency interpolation with new object returns tuple
calling _interp_freq with new_object=true gives a tuple with a uv beam object as the zeroth entry and 'None' as the first entry. Is this the desired behavior?

### PR DESCRIPTION
**Pull request by bhazelton**
## Description

Add option to return a new beam object from `UVBeam.interp`. Remove corresponding functionality from the private `_interp_freq` method.

## Motivation and Context

closes #622 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change (documentation changes only)
- [ ] Version change
- [ ] Build or continuous integration change

## Checklist:

- [x] I have read the [contribution guide](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/master/.github/CONTRIBUTING.md).
- [x] My code follows the code style of this project.

New feature checklist:
- [x] I have added or updated the docstrings associated with my feature using the [numpy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html).
- [ ] I have updated the tutorial to highlight my new feature (if appropriate).
- [x] I have added tests to cover my new feature.
- [x] All new and existing tests pass in both python 2 and python 3.
- [x] I have updated the [CHANGELOG](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/master/CHANGELOG.md).

Breaking change checklist:  
- [x] I have updated the docstrings associated with my change using the [numpy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html).
- [ ] I have updated the tutorial to reflect my changes (if appropriate).
- [ ] My change includes backwards compatibility and deprecation warnings (if possible).
- [x] I have added tests to cover my changes.
- [x] All new and existing tests pass in both python 2 and python 3.
- [x] I have updated the [CHANGELOG](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by jpober** [comment]
Sam is on vacation until next week.  We'll take a look then and see if this is a clean fix for our use case.  (PS: Why can't I tag her here?  She opened an issue, but maybe you can only tag people that are part of the team?)

**Comment by mkolopanis** [comment]
It's possible you might be able to tag but it won't autocomplete for you? let's try: @samanthamcgraw

**Comment by bhazelton** [comment]
Great. @aelanman can you check to make sure this doesn't break anything in healvis or pyuvsim?

**Comment by aelanman** [comment]
@bhazelton It does seem to have broken some pyuvsim tests, but this might just be issues that can be addressed in pyuvsim. One is because `UVBeam.interp` no longer accepts the keyword `freq_interp_kind`. I've fixed that by setting the attribute on each UVBeam object.

There's another that's a little harder to track down. One test is bringing up an error from scipy.interp1d:
`ValueError: The number of derivatives at boundaries does not match: expected 2, got 0+0`

This is coming from the frequency interpolation step.

`healvis` on the other hand needs to be updated to call the new functions, instead of the private `_interp_freq` method.

**Comment by aelanman** [comment]
Update -- This last error is caused by using cubic frequency interpolation instead of linear. Curious that this test passed before...

I realized that although the antenna class functions accept `freq_interp_kind` as a keyword, there is no way for the user to set interpolation methods on the UVBeams. I'll make an issue on pyuvsim for that.

**Comment by bhazelton** [comment]
@jpober @samanthamcgraw I think I fixed the bug you told me about on this branch. Sorry for the delay! Let me know if you still have trouble.

**Comment by jpober** [comment]
This is working for us, thanks @bhazelton.  I'm happy to approve the PR, but @aelanman can you confirm that nothing will break for you if this change gets into master?

**Pull request merged**
