### PR TITLE
Add support for selecting on polarization strings

### LINKED ISSUE #1023: Select on polarization strings
UVData select only accepts polarization numbers and not polarization strings. It would be ideal to be able to use pol strings as well. For example:

`uv.select(polarizations='xx')`

### PR DESCRIPTION
**Pull request by bhazelton**
## Description

Add full support for selecting on polarization strings on all our objects -- both the canonical names (e.g. "xx" or "rr") and the physical dipole orientation names (e.g. "nn" or "ee") if the `x_orientation` attribute is set. There was already support on UVData and UVFlag for selecting on polarization strings, but it was undocumented and not fully tested.

I also did some minor cleanup and add a couple of missing details to the tutorial along with the tutorial updates for this new functionality.

## Motivation and Context

closes #1023 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change (documentation changes only)
- [ ] Version change
- [ ] Build or continuous integration change

## Checklist:

- [x] I have read the [contribution guide](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/main/.github/CONTRIBUTING.md).
- [x] My code follows the code style of this project.

New feature checklist:
- [x] I have added or updated the docstrings associated with my feature using the [numpy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html).
- [x] I have updated the tutorial to highlight my new feature (if appropriate).
- [x] I have added tests to cover my new feature.
- [x] All new and existing tests pass.
- [x] I have updated the [CHANGELOG](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/main/CHANGELOG.md).

### CODE REVIEW

**Comment by bhazelton** [comment]
@dstorer and @Zhilei I think this addresses your issue, I'd love your feedback if you have time to take a look.

**Comment by Zhilei** [comment]
Great! Thank you so much for implementing the new feature!
I was wondering what are the related functions for this, `select_polstr`?
In addition, I guess this is currently only in pyuvdata but not in pyuvbeam, is that right?

**Comment by bhazelton** [comment]
@Zhilei There's not a new method, it's an update to the existing `select` method, and there's not a new keyword, it's an update to let the `polarization` keyword accept strings as well as integers. This PR adds it to all the objects: UVData, UVCal, UVBeam and UVFlag.

**Comment by Zhilei** [comment]
Oh, wow. Great!
Thanks for the explanation!

**Comment by Zhilei** [comment]
BTW, just to double-check: 
Right now if I select polarization `nn`, it will consider the `x_orientation` attribute and map `nn` to `x` or `y` accordingly, right?

**Comment by bhazelton** [comment]
Yes, if the `x_orientation` keyword is set on the object.

**Review by mkolopanis — APPROVED** [review]
This looks pretty good to me. Tutorial seems good on the read the docs build too. Thanks @bhazelton

**Pull request merged**
