### PR TITLE
Adjust up/down sample in time logic.

### LINKED ISSUE #773: Wrong number of blts during downsample
OS: ubuntu 18.04 
pyuvdata version: 2.0.1.dev26+gfbca23c4
python version: 3.8.1
Telescope: MWA phase 2 compact
obsids: `[1160576480,1160576848,1160576968,1160577096,1160577216,1160577336,1160577456,1160577584,1160577704,1160577824,1160578072,1160578192] `
when attempting to downsample in time a set of redundant baseline (baselines like (61, 58) see picture below) from 2.0s integration times to 4.0s integration times, the wrong number of blts is being returned by downsample in time. See attached traceback. 

```
uv.resample_in_time(4.0, only_downsample=True, keep_ragged=True)
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-42-ade2d3ae7c8f> in <module>
----> 1 uv.resample_in_time(4.0, only_downsample=True, keep_ragged=True)

~/src/anaconda/envs/py38/lib/python3.8/site-packages/pyuvdata/uvdata/uvdata.py in resample_in_time(self, target_time, only_downsample, only_upsample, blt_order, minor_order, keep_ragged, summing_correlator_mode, allow_drift)
   5655 
   5656         if downsample:
-> 5657             self.downsample_in_time(
   5658                 target_time,
   5659                 blt_order=blt_order,

~/src/anaconda/envs/py38/lib/python3.8/site-packages/pyuvdata/uvdata/uvdata.py in downsample_in_time(self, min_int_time, blt_order, minor_order, keep_ragged, summing_correlator_mode, allow_drift)
   5566 
   5567         # make sure we've populated the right number of baseline-times
-> 5568         assert temp_idx == temp_Nblts, ("Wrong number of baselines. Got {:d}, "
   5569                                         "expected {:d}. This is a bug, please "
   5570                                         "make an issue at https://github.com/"

AssertionError: Wrong number of baselines. Got 12218, expected 13776. This is a bug, please make an issue at https://github.com/RadioAstronomySoftwareGroup/pyuvdata/issues
```
image

### LINKED ISSUE #782: Silent failure in resample_in_time
the explicit checks that the target integration must be either 2 * minimum integration time to downsample or 1/2 the max integration time to upsample results in a silent failure when calling `resample_in_time` with some target times. 
MWA data identical to #773 
```
uv1.resample_in_time(3,  keep_ragged=False)
uv1.integration_time
[output]
array([1.99813843, 1.99813843, 1.99813843, 1.99813843, 1.99813843,
       1.99813843, 1.99813843, 1.99813843, 1.99813843, 1.99813843,
       1.99813843, 1.99813843, 1.99813843, 1.99813843, 1.99813843,
       1.99813843, 1.99813843, 1.99813843, 1.99813843, 1.99813843,
       1.99813843, 1.99813843, 1.99813843, 1.99813843, 1.99813843,
       1.99813843, 1.99813843, 1.99813843, 1.99813843, 1.99813843,
       1.99813843, 1.99813843, 1.99813843, 1.99813843, 1.99813843,
       1.99813843, 1.99813843, 1.99813843, 1.99813843, 1.99813843,
       1.99813843, 1.99813843, 1.99813843, 1.99813843, 1.99813843,
       1.99813843, 1.99813843, 1.99813843, 1.99813843, 1.99813843,
       1.99813843, 1.99813843, 1.99813843, 1.99813843, 1.99813843,
       1.99813843, 1.99813843, 1.99813843, 1.99813843, 1.99813843,
       1.99813843, 1.99813843, 1.99813843, 1.99813843, 1.99813843,
       1.99813843, 1.99813843, 1.99813843, 1.99813843, 1.99813843,
       1.99813843, 1.99813843, 1.99813843, 1.99813843, 1.99813843,
       1.99813843, 1.99813843, 1.99813843, 1.99813843, 1.99813843,.......
```
but calling downsample_in_time actually attempts the resample
```
uv1.downsample_in_time(3,  keep_ragged=False)
There is a gap in the times of baseline (61, 58). The output may include averages across long time gaps.
There is a gap in the times of baseline (62, 59). The output may include averages across long time gaps.
There is a gap in the times of baseline (63, 60). The output may include averages across long time gaps.
There is a gap in the times of baseline (66, 62). The output may include averages across long time gaps.
There is a gap in the times of baseline (67, 63). The output may include averages across long time gaps.
There is a gap in the times of baseline (68, 64). The output may include averages across long time gaps.
There is a gap in the times of baseline (69, 65). The output may include averages across long time gaps.
There is a gap in the times of baseline (72, 67). The output may include averages across long time gaps.
There is a gap in the times of baseline (73, 68). The output may include averages across long time gaps.
There is a gap in the times of baseline (74, 69). The output may include averages across long time gaps.
There is a gap in the times of baseline (75, 71). The output may include averages across long time gaps.
There is a gap in the times of baseline (78, 74). The output may include averages across long time gaps.
There is a gap in the times of baseline (80, 75). The output may include averages across long time gaps.
There is a gap in the times of baseline (81, 76). The output may include averages across long time gaps.
There is a gap in the times of baseline (82, 77). The output may include averages across long time gaps.
There is a gap in the times of baseline (84, 80). The output may include averages across long time gaps.
There is a gap in the times of baseline (85, 81). The output may include averages across long time gaps.
There is a gap in the times of baseline (86, 82). The output may include averages across long time gaps.
There is a gap in the times of baseline (87, 83). The output may include averages across long time gaps.
There is a gap in the times of baseline (89, 86). The output may include averages across long time gaps.
There is a gap in the times of baseline (90, 87). The output may include averages across long time gaps.
There is a gap in the times of baseline (91, 88). The output may include averages across long time gaps.
There is a gap in the times of baseline (96, 93). The output may include averages across long time gaps.
There is a gap in the times of baseline (97, 94). The output may include averages across long time gaps.
There is a gap in the times of baseline (98, 95). The output may include averages across long time gaps.
There is a gap in the times of baseline (101, 97). The output may include averages across long time gaps.
There is a gap in the times of baseline (102, 98). The output may include averages across long time gaps.
There is a gap in the times of baseline (104, 100). The output may include averages across long time gaps.
There is a gap in the times of baseline (107, 102). The output may include averages across long time gaps.
There is a gap in the times of baseline (109, 104). The output may include averages across long time gaps.
There is a gap in the times of baseline (110, 106). The output may include averages across long time gaps.
There is a gap in the times of baseline (113, 109). The output may include averages across long time gaps.
There is a gap in the times of baseline (115, 110). The output may include averages across long time gaps.
There is a gap in the times of baseline (116, 111). The output may include averages across long time gaps.
There is a gap in the times of baseline (117, 112). The output may include averages across long time gaps.
There is a gap in the times of baseline (119, 115). The output may include averages across long time gaps.
There is a gap in the times of baseline (120, 116). The output may include averages across long time gaps.
There is a gap in the times of baseline (121, 117). The output may include averages across long time gaps.
There is a gap in the times of baseline (122, 118). The output may include averages across long time gaps.
There is a gap in the times of baseline (124, 121). The output may include averages across long time gaps.
There is a gap in the times of baseline (125, 122). The output may include averages across long time gaps.
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-114-429254b353eb> in <module>
----> 1 uv1.downsample_in_time(3,  keep_ragged=False)

~/src/anaconda/envs/py38/lib/python3.8/site-packages/pyuvdata/uvdata/uvdata.py in downsample_in_time(self, min_int_time, blt_order, minor_order, keep_ragged, summing_correlator_mode, allow_drift)
   4093 
   4094         # make sure we've populated the right number of baseline-times
-> 4095         assert temp_idx == temp_Nblts, ("Wrong number of baselines. Got {:d}, "
   4096                                         "expected {:d}. This is a bug, please "
   4097                                         "make an issue at https://github.com/"

AssertionError: Wrong number of baselines. Got 205, expected 287. This is a bug, please make an issue at https://github.com/RadioAstronomySoftwareGroup/pyuvdata/issues
```

### PR DESCRIPTION
**Pull request by mkolopanis**
## Description

Fix logic in `downsample_in_time` to correctly calculate the number of new blts. Also prevent silent failure in `resample_in_time` by adding a warning.

## Motivation and Context

closes #773
closes #782

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change (documentation changes only)
- [ ] Version change
- [ ] Build or continuous integration change

## Checklist:

- [x] I have read the [contribution guide](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/master/.github/CONTRIBUTING.md).
- [x] My code follows the code style of this project.

Bug fix checklist:
- [x] My fix includes a new test that breaks as a result of the bug (if possible).
- [x] All new and existing tests pass.
- [x] I have updated the [CHANGELOG](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by bhazelton** [comment]
@adampbeardsley are you willing to review this one?

**Comment by bhazelton** [comment]
oops! I marked the wrong issue. I'll fix the comment.

**Comment by adampbeardsley** [comment]
Ok, my only other note then is that the data file Matt added has data all zeros and flags all True. It doesn't matter for this specific test, but since we're adding a file we might as well add one that might be more useful for other purposes. I'll leave that up to @bhazelton @mkolopanis

**Comment by mkolopanis** [comment]
Ah yes. I will change out the file

**Pull request merged**
